spring.application.name=PizzaHut

# SQLite
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.url=jdbc:sqlite:data/pizzahut2.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.show-sql=true

# Logging
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.tuapp=DEBUG
logging.file.name=logs/pizzahut2.log
logging.file.path=logs/
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.max-file-size=10MB
